// Code generated by protoc-gen-go from "request.proto"
// DO NOT EDIT!

package main

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type REQUEST_TYPE int32

const (
	REQUEST_TYPE_CREATE REQUEST_TYPE = 1
	REQUEST_TYPE_READ   REQUEST_TYPE = 2
	REQUEST_TYPE_UPDATE REQUEST_TYPE = 3
	REQUEST_TYPE_DELTE  REQUEST_TYPE = 4
	REQUEST_TYPE_CLEAR  REQUEST_TYPE = 5
	REQUEST_TYPE_STOP   REQUEST_TYPE = 6
)

var REQUEST_TYPE_name = map[int32]string{
	1: "CREATE",
	2: "READ",
	3: "UPDATE",
	4: "DELTE",
	5: "CLEAR",
	6: "STOP",
}
var REQUEST_TYPE_value = map[string]int32{
	"CREATE": 1,
	"READ":   2,
	"UPDATE": 3,
	"DELTE":  4,
	"CLEAR":  5,
	"STOP":   6,
}

func (x REQUEST_TYPE) Enum() *REQUEST_TYPE {
	p := new(REQUEST_TYPE)
	*p = x
	return p
}
func (x REQUEST_TYPE) String() string {
	return proto.EnumName(REQUEST_TYPE_name, int32(x))
}
func (x REQUEST_TYPE) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *REQUEST_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(REQUEST_TYPE_value, data, "REQUEST_TYPE")
	if err != nil {
		return err
	}
	*x = REQUEST_TYPE(value)
	return nil
}

type STATES_CODE int32

const (
	STATES_CODE_OK   STATES_CODE = 1
	STATES_CODE_BUSY STATES_CODE = 2
	STATES_CODE_ERR  STATES_CODE = 3
)

var STATES_CODE_name = map[int32]string{
	1: "OK",
	2: "BUSY",
	3: "ERR",
}
var STATES_CODE_value = map[string]int32{
	"OK":   1,
	"BUSY": 2,
	"ERR":  3,
}

func (x STATES_CODE) Enum() *STATES_CODE {
	p := new(STATES_CODE)
	*p = x
	return p
}
func (x STATES_CODE) String() string {
	return proto.EnumName(STATES_CODE_name, int32(x))
}
func (x STATES_CODE) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *STATES_CODE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(STATES_CODE_value, data, "STATES_CODE")
	if err != nil {
		return err
	}
	*x = STATES_CODE(value)
	return nil
}

type IPRequest struct {
	RequestType      *REQUEST_TYPE `protobuf:"varint,1,opt,name=request_type,enum=main.REQUEST_TYPE" json:"request_type,omitempty"`
	Ipaddresses      [][]byte      `protobuf:"bytes,2,rep,name=ipaddresses" json:"ipaddresses,omitempty"`
	Timeout          *int32        `protobuf:"varint,3,opt,name=timeout" json:"timeout,omitempty"`
	Rate             *int32        `protobuf:"varint,4,opt,name=rate" json:"rate,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (this *IPRequest) Reset()         { *this = IPRequest{} }
func (this *IPRequest) String() string { return proto.CompactTextString(this) }
func (*IPRequest) ProtoMessage()       {}

func (this *IPRequest) GetRequestType() REQUEST_TYPE {
	if this != nil && this.RequestType != nil {
		return *this.RequestType
	}
	return 0
}

func (this *IPRequest) GetTimeout() int32 {
	if this != nil && this.Timeout != nil {
		return *this.Timeout
	}
	return 0
}

func (this *IPRequest) GetRate() int32 {
	if this != nil && this.Rate != nil {
		return *this.Rate
	}
	return 0
}

type Response struct {
	StatCode         *STATES_CODE `protobuf:"varint,1,opt,name=stat_code,enum=main.STATES_CODE" json:"stat_code,omitempty"`
	Msg              []byte       `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (this *Response) Reset()         { *this = Response{} }
func (this *Response) String() string { return proto.CompactTextString(this) }
func (*Response) ProtoMessage()       {}

func (this *Response) GetStatCode() STATES_CODE {
	if this != nil && this.StatCode != nil {
		return *this.StatCode
	}
	return 0
}

func (this *Response) GetMsg() []byte {
	if this != nil {
		return this.Msg
	}
	return nil
}

func init() {
	proto.RegisterEnum("main.REQUEST_TYPE", REQUEST_TYPE_name, REQUEST_TYPE_value)
	proto.RegisterEnum("main.STATES_CODE", STATES_CODE_name, STATES_CODE_value)
}
